ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 0

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "banner_overlay_w_heart"
file = "images/banner_overlay_w_heart.png"
startx = 754
starty = 660
priority = 3

[[structure]]
name = "tagpro"
file = "images/tagpro.png"
startx = 200
starty = 450
priority = 2

[[structure]]
name = "komi"
file = "images/komi.png"
startx = 713
starty = 646
priority = 2

[[structure]]
name = "aunty-donna"
file = "images/aunty-donna.png"
startx = 738
starty = 648
priority = 2

[[structure]]
name = "throwback"
file = "images/throwback.png"
startx = 747
starty = 667
priority = 2
