ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 0

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "banner_overlay_w_heart"
file = "images/banner_overlay_w_heart.png"
startx = 754
starty = 660
priority = 3

[[structure]]
name = "tagpro"
file = "images/tagpro.png"
startx = 199
starty = 451
priority = 2
